language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
deploy:
  provider: rubygems
  api_key:
    secure: UgsFjQHG9CvXih7iQ18Diew4LxJOZtfoQ84nXMODNchUFSBXrJpbK67me6F19EHbeYiSoVNxXiTDLUIMvETXfE50xGfc08Wjag5v+S7+T82I0MN4dqv1eM4kPjGSbaavEcj9ma8qPGW3QqaU21fRWsNSl4btnh1kUtFltGYvhzA=
  gem: fluxapi
  on:
    tags: true
    repo: bastilian/fluxapi
